//! C `printf` `%e` / `%f` / `%g` formatting, byte-exact.
//!
//! Every floating-point value printed anywhere in this workspace goes
//! through these helpers (workspace rule 5). Rust's `{:e}` is never used:
//! its exponent form (`1.5e2`) differs from C (`1.500000e+02`).
//!
//! The unit tests assert against 1500+ vectors generated by the system C
//! library's `printf` (`sundials_utils_cvec.txt`).

/// C `printf("%.*e", prec, x)`.
pub fn fmt_e(x: f64, prec: usize) -> String {
    if x.is_nan() {
        return "nan".to_string();
    }
    if x.is_infinite() {
        return if x < 0.0 { "-inf" } else { "inf" }.to_string();
    }
    let s = format!("{:.*e}", prec, x);
    let epos = s.rfind('e').expect("float e-format always has an exponent");
    let mant = &s[..epos];
    let exp = &s[epos + 1..];
    let (sign, digits) = match exp.strip_prefix('-') {
        Some(d) => ('-', d),
        None => ('+', exp),
    };
    format!("{mant}e{sign}{digits:0>2}")
}

/// C `printf("%.*f", prec, x)`.
pub fn fmt_f(x: f64, prec: usize) -> String {
    if x.is_nan() {
        return "nan".to_string();
    }
    if x.is_infinite() {
        return if x < 0.0 { "-inf" } else { "inf" }.to_string();
    }
    format!("{:.*}", prec, x)
}

/// C `printf("%.*g", prec, x)`.
pub fn fmt_g(x: f64, prec: usize) -> String {
    if x.is_nan() {
        return "nan".to_string();
    }
    if x.is_infinite() {
        return if x < 0.0 { "-inf" } else { "inf" }.to_string();
    }
    let p = if prec == 0 { 1 } else { prec };
    if x == 0.0 {
        return if x.is_sign_negative() { "-0" } else { "0" }.to_string();
    }
    // C99: X = the exponent of the %e conversion at precision P-1 (i.e.
    // after rounding); style e iff X < -4 or X >= P, else style f with
    // precision P-1-X; trailing zeros (and a bare '.') are removed.
    let es = format!("{:.*e}", p - 1, x);
    let epos = es.rfind('e').expect("float e-format always has an exponent");
    let e10: i32 = es[epos + 1..].parse().expect("exponent is an integer");
    if e10 < -4 || e10 >= p as i32 {
        let mant = strip_trailing_zeros(&es[..epos]);
        let exp = &es[epos + 1..];
        let (sign, digits) = match exp.strip_prefix('-') {
            Some(d) => ('-', d),
            None => ('+', exp),
        };
        format!("{mant}e{sign}{digits:0>2}")
    } else {
        let fprec = (p as i32 - 1 - e10) as usize;
        strip_trailing_zeros(&format!("{:.*}", fprec, x)).to_string()
    }
}

fn strip_trailing_zeros(s: &str) -> &str {
    if s.contains('.') {
        let s = s.trim_end_matches('0');
        s.strip_suffix('.').unwrap_or(s)
    } else {
        s
    }
}

/// C `printf("%*.*e", width, prec, x)` (right-justified, space-padded).
pub fn fmt_ew(x: f64, width: usize, prec: usize) -> String {
    format!("{:>width$}", fmt_e(x, prec))
}

/// C `printf("%*.*f", width, prec, x)`.
pub fn fmt_fw(x: f64, width: usize, prec: usize) -> String {
    format!("{:>width$}", fmt_f(x, prec))
}

/// C `printf("%*.*g", width, prec, x)`.
pub fn fmt_gw(x: f64, width: usize, prec: usize) -> String {
    format!("{:>width$}", fmt_g(x, prec))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Same values, same order, as the generator that produced
    /// `sundials_utils_cvec.txt` (system C printf ground truth).
    const VALS: [f64; 41] = [
        0.0,
        -0.0,
        1.0,
        -1.5,
        2.5,
        0.5,
        0.1,
        1.0 / 3.0,
        9.999999999e-5,
        1.5e-300,
        1234567.891,
        6.02214076e23,
        1e100,
        3.9e-105,
        5e-324,
        2.2250738585072014e-308, // DBL_MIN
        1.7976931348623157e308,  // DBL_MAX
        9.999999e99,
        100000.0,
        1000000.0,
        1e-4,
        1e-5,
        120.0,
        0.000123456,
        999999.5,
        1234.5,
        123456789.0,
        -987.654321,
        42.0,
        0.25,
        1.0e-9,
        7.389056098930650,
        2.718281828459045,
        3.141592653589793,
        1.7e-8,
        98765.4321e-12,
        5.5,
        -5.5,
        6.5,
        0.0625,
        1048576.0,
    ];

    #[test]
    fn matches_c_printf_vectors() {
        let data = include_str!("sundials_utils_cvec.txt");
        let mut checked = 0usize;
        for line in data.lines() {
            let mut it = line.splitn(4, '|');
            let kind = it.next().expect("kind field");
            let idx = it.next().expect("idx field");
            let prec: usize = it.next().expect("prec field").parse().expect("prec");
            let expected = it.next().expect("expected field");
            let (x, label): (f64, String) = match idx {
                "inf" => (f64::INFINITY, "inf".to_string()),
                "ninf" => (f64::NEG_INFINITY, "ninf".to_string()),
                "nan" => (f64::NAN, "nan".to_string()),
                n => {
                    let i: usize = n.parse().expect("value index");
                    (VALS[i], format!("VALS[{i}]"))
                }
            };
            let got = match kind {
                "e" => fmt_e(x, prec),
                "f" => fmt_f(x, prec),
                "g" => fmt_g(x, prec),
                other => panic!("unknown kind {other}"),
            };
            assert_eq!(got, expected, "fmt_{kind}({label}={x:?}, {prec})");
            checked += 1;
        }
        assert_eq!(checked, 1565, "all C vectors exercised");
    }

    #[test]
    fn width_helpers_right_justify() {
        assert_eq!(fmt_ew(1.5, 14, 6), "  1.500000e+00");
        assert_eq!(fmt_fw(3.14159265, 10, 4), "    3.1416");
        assert_eq!(fmt_gw(100000.0, 8, 6), "  100000");
        // width smaller than the output never truncates (C semantics)
        assert_eq!(fmt_ew(1.5, 3, 6), "1.500000e+00");
    }
}

/// C `SUN_FORMAT_E` = `"% .15e"` (space flag: non-negatives get a space).
pub fn sun_format_e(x: f64) -> String {
    let s = fmt_e(x, 15);
    if s.starts_with('-') {
        s
    } else {
        format!(" {s}")
    }
}

/// C `SUN_FORMAT_G` = `"%.15g"`.
pub fn sun_format_g(x: f64) -> String {
    fmt_g(x, 15)
}

/// C `SUN_FORMAT_SG` = `"%+.15g"`.
pub fn sun_format_sg(x: f64) -> String {
    let s = fmt_g(x, 15);
    if s.starts_with('-') {
        s
    } else {
        format!("+{s}")
    }
}
